### ISSUE TITLE
Universe / Sub or Net numbers convert issue on oled

### ISSUE THREAD

**Issue by Kawaiito** [ArtGateOne/ArtGateOne-DMX#2]
Hello when i put numbers by subnet / net or universe there make numbers higher than 9 to letters so 10 = A /11= B / on the oled  display

**Comment by ArtGateOne** [comment]
Everything is correct - it was the idea that these data should be displayed in the hexadecimal system (so that they fit nicely on the display - anyway, they are displayed in the same way in MALighting dot2). And that's not a mistake.

Of course, if you don't like this form of presentation on OLED - you can change it.

I don't have an Arduino right now to check it and if it will be correct - but try it.

first solution.
on lines 703 705 and 707 - remove ", HEX"

possibly replace with ", DEC"


Better yet, delete lines 702 to 707 and put something like this there:

oled.print("Universe = ");
oled.print(intUniverse);
