### ISSUE TITLE
Parse variable length ArtDmx packets

### ISSUE THREAD

**Issue by Breina** [ArtGateOne/ArtGateOne-DMX#4]
The ArtNet 4 spec includes a `length` field, which indicates how many channels are included in the packet:

![image](https://user-images.githubusercontent.com/3009914/210536784-fff1d3a3-2e50-47d4-8465-b3f4162414ff.png)

The current implementation is hardcoded on the full 512 set of channels:

https://github.com/ArtGateOne/ArtGateOne-DMX/blob/master/ArtGateOne_DMX_1.3/ArtGateOne_DMX_1.3.ino#L656

This causes ArtDmx packets that only send the requirement amount of channels, without 0 padding, to not be properly parsed.

**Comment by ArtGateOne** [comment]
The line you indicated - is only responsible for saving all 512 channels to the eeprom memory - and they are loaded - when the BOOT SCENE option is enabled and Arduino does not receive any artnet packet. Until it receives an artnet signal - this static scene controls our lights.

**Comment by Breina** [comment]
Apologies, I merely skimmed the codebase for possible causes.

One of our users [did report](https://community.home-assistant.io/t/dmx-lighting/2248/332?u=breina) improper handling of non-full universes (full ones did work). Here is an example ArtDMX packet with 12 0xFF channels:

```
0000   41 72 74 2d 4e 65 74 00 00 50 00 0e 01 00 00 00  Art-Net..P......
0010   00 0c ff ff ff ff ff ff ff ff ff ff ff ff        ..............
```

Is it possible to verify this behaviour for such packets?

**Comment by ArtGateOne** [comment]
My code is very simplified to make the whole procedure of receiving and processing artnet packets as fast as possible.

The code first checks the size of the data
line 374
    if (packetSize == 530)

If the packet size is correct - the code then checks the universe number and if it is the same as we have selected in the arduino configuration - it is read and sent as dmx data.

So if the program/console sends artnet packets of smaller size - these are not recognized.

Because my code takes up almost all of the arduino uno's memory - it's limited to only recognizing full artnet artdmx packets, and art poll

**Comment by Breina** [comment]
Ah I see, thanks for the explanation. I'll close the issue in that case. :)

Perhaps you can add a warning in the readme for this edge case, might help some future troubleshooters. But that's up to you.
